config/routes.rb
Rails.application.routes.draw do

  # get 'user_sessions/new'
  # get 'user_sessions/create'
  resources :users #, only: [:index, show]
  resources :projects
  resources :branches
  resources :employees
  resources :timesheets
  #resources :requisitions
  resources :leave_requests
  resources :inventory_items
  resources :inventory_item_categories
  resources :inventory_item_thresholds
  resources :inventory_item_types
  resources :project_tasks
  resources :business_assets
  resources :time_sheet_tasks
  resources :project_task_assignments
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'travel_requests/new', to: 'travel_requests#new', as: :save_budget_details
  post 'travel_requests/create', to: 'travel_requests#create', as: :create_travel_requests
  get 'travel_requests/:id', to: 'travel_requests#show', as: :travel_request_show

  
  put 'timesheets/:id/submit_timesheet', to: 'timesheets#submit_timesheet'
  put 'timesheets/:id/approve_timesheet', to: 'timesheets#approve_timesheet'
  put 'timesheets/:id/reject_timesheet', to: 'timesheets#reject_timesheet', as: :reject_timesheet
  put 'timesheets/:id/recall_timesheet', to: 'timesheets#recall_timesheet'
  put 'timesheets/:id/re-open_timesheet', to: 'timesheets#reopen_timesheet'
  put 'timesheets/:id/re-submit_timesheet', to: 'timesheets#resubmit_timesheet'
  get 'my_timesheet', to: 'timesheets#show', as: :my_timesheet

  get 'settings/index'
  get 'settings/new'
  post 'settings/create'
  get 'settings/edit'

  get 'requisitions', to: 'requisitions#index'
  get 'requisitions/new', to: 'requisitions#new', defaults: { format: :turbo_stream }
  post 'requisitions/create'
  get 'requisitions/:id', to: 'requisitions#show'
  get 'requisitions/edit'
  patch 'requisitions/:id', to: 'requisitions#resubmit_request', as: :resubmit_request_requisition
  post '/clear_flash', to: 'application#clear_flash', as: :clear_flash

  put 'requisitions/:id/approve_request', to: 'requisitions#approve_request'
  put 'requisitions/:id/re-submit_request', to: 'requisitions#resubmit_request'
  put 'requisitions/:id/approve_funds', to: 'requisitions#approve_funds'
  put 'requisitions/:id/deny_funds', to: 'requisitions#deny_funds'
  put 'requisitions/:id/release_funds', to: 'requisitions#release_funds'
  put 'requisitions/:id/rescind_request', to: 'requisitions#rescind_request'
  put 'requisitions/:id/reject_request', to: 'requisitions#reject_request'
  put 'requisitions/:id/recall_request', to: 'requisitions#recall_request'
  put 'requisitions/:id/collect_funds', to: 'requisitions#collect_funds'
  put 'requisitions/:id/disburse_funds', to: 'requisitions#disburse_funds'
  patch 'requisitions/:id/liquidate_funds', to: 'requisitions#liquidate_funds', as: :liquidate_funds_requisition

  namespace :requisitions do
    resources :purchase_requests do
      member do
        # Define custom routes for purchase_requests here
      end
    end
  end

  put 'leave_requests/:id/approve_leave', to: 'leave_requests#approve_leave'
  put 'leave_requests/:id/cancel_leave', to: 'leave_requests#cancel_leave'
  put 'leave_requests/:id/deny_leave', to: 'leave_requests#deny_leave'
  put 'leave_requests/:id/rescind_request', to: 'leave_requests#rescind_request'

  get 'reports/index'
  get 'reports/new'
  get 'reports/create'
  get 'reports/edit'
  get 'reports/monthly_org_loe_report'

  get 'users/index'
  get 'forgot_password', to: 'users#forgot_password'
  post 'password_reset_forget', to: 'users#password_reset_forget'
  put 'users/:id/password_reset', to: 'users#password_reset'
  get 'main/home'
  get 'about', to: 'main#about'

  get "generate_report", to: 'reports#show', as: "generate_report", defaults: { format: :turbo_stream }

  get "logout", to: "user_sessions#destroy"
  resources :asset_categories

  get 'tc_dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "main#home"
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController # rubocop:disable Style/Documentation
  before_action :can_access?, only: %i[create edit update show index]
  def index
    @list_employees = Employee.where(still_employed: true).collect { |x| x.person }
  end

  def show
  end

  def new
    @new_employee = Employee.new
  end

  def process_params # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    person_params = params[:person].dup
    employee_params = params[:employee].dup
    supervision_params = params[:supervision].dup

    # Person
    person_params[:first_name] = person_params[:first_name].strip.capitalize.gsub(/[^a-zA-Z]/, '')
    person_params[:middle_name] = person_params[:middle_name].to_s.strip.gsub(/[^a-zA-Z']/, '').capitalize
    person_params[:last_name] = person_params[:last_name].strip.capitalize.gsub(/[^a-zA-Z]/, '')
    person_params[:gender] = person_params[:gender].strip
    person_params[:marital_status] = person_params[:marital_status].strip
    person_params[:primary_phone] = person_params[:primary_phone].strip.gsub(/[^0-9]/, '')
    person_params[:alt_phone] = person_params[:alt_phone].strip.gsub(/[^0-9]/, '')
    person_params[:email_address] = person_params[:email_address].strip
    person_params[:official_email] = person_params[:official_email].strip
    person_params[:postal_address] = person_params[:postal_address].strip.gsub(/\n/, ',')
    person_params[:residential_address] = person_params[:residential_address].strip.gsub(/\n/, ',')
    person_params[:landmark] = person_params[:landmark].strip.gsub(/\n/, ',')

    # Employee
    employee_params[:branch] = employee_params[:branch].to_i

    # projects
    projects_params = params[:projects].map { |p| p.permit(:project, :allocated_effort) }

    # supervision
    supervisor_name = params[:supervision][:supervisor]
    first_name, last_name = supervisor_name.split(' ', 2)
    supervision_params[:supervisor] = Person.where(first_name: first_name, last_name: last_name) # rubocop:disable Style/HashSyntax
                                            .pluck(:person_id).first
    supervision_params[:started_on] = params[:supervision][:started_on]

    {
      person: person_params.permit(:first_name, :middle_name, :last_name, :birth_date, :gender, :marital_status,
                                   :primary_phone, :alt_phone, :email_address, :official_email, :postal_address,
                                   :residential_address, :landmark).to_h,

      employee: employee_params.permit(:employment_date, :designated_role, :designation_start_date, :branch,
                                       :departments).to_h,

      supervision: supervision_params.permit(:supervisor, :started_on).to_h,

      project: projects_params

    }
  end

  def create
    begin # rubocop:disable Style/RedundantBegin
      EmployeeCreationService.call(process_params, session)
      UserMailer.welcome_email(session[:last_username], session[:last_password]).deliver_now
      flash[:notice] = 'Employee added successfully!'
      redirect_to '/employees'
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = "Error updating employee details!: #{e}"
    end
  end

  def edit
    @user = @current_user
    @person = Person.find(params[:id])
    @employee = Employee.find(params[:id])
    @project = Project.all.collect { |x| [x.project_name, x.id] }
  end

  def update
    @person = Person.find(params[:id])
    @employee = Employee.find(params[:id])
    @designated_role = Designation.where(designated_role: employee_params[:designated_role])
    if @person.update(first_name: params[:person][:first_name], middle_name: params[:person][:middle_name],
                      last_name: params[:person][:last_name],
                      primary_phone: params[:person][:primary_phone], alt_phone: params[:person][:alt_phone],
                      marital_status: params[:person][:marital_status], residential_address: params[:person][:residential_address])
      if @employee.update(employment_date: params[:person][:employment_date])
        if @designated_role.update(designated_role: params[:designated_role])
          redirect_to '/employees'
          flash[:notice] = 'Successfully updated designation.'
        end
        flash[:notice] = 'Successfully updated employee.'
      end
      flash[:notice] = 'Successfully updated person.'
    end
  end

  def can_access?
    permitted_users = Designation.where(designated_role: ['Executive Director', 'Administration Officer',
                                                          'Administraton & HR Officer', 'Human Resources Officer', 'Informatics Product Developer']).pluck(:designation_id) # rubocop:disable Layout/LineLength
    current_designation = EmployeeDesignation.where(employee_id: @current_user.id).pluck(:designation_id)
    return unless (current_designation & permitted_users).empty?

    flash[:error] = 'You do not have permission to access this page.'
    redirect_to root_path
  end

  def employee_params
    params.permit(:first_name, :middle_name, :last_name, :birth_date, :gender, :marital_status,
                  :primary_phone, :alt_phone, :email_address, :postal_address, :official_email,
                  :residential_address, :landmark, :employment_date, :designated_role, :supervisor, :started_on,
                  :project, :allocated_effort)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_edit_employee.erb
<%= form_with model: @person, method: "PUT",  url: "/employees/#{@person.id}" , data: {'turbo-frame' => '_top'} do |form|%>
  <div class="row">
    <div class="col mb-3">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, value: @person.first_name, class: 'form-control', required: true %>
    </div>
    <div class="col mb-3">
      <%= form.label :middle_name %>
      <%= form.text_field :middle_name, value: @person.middle_name, class: 'form-control', required: true %>
    </div>
    <div class="col mb-3">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, value: @person.last_name, class: 'form-control', required: true %>
    </div>
  </div>
<!--  <div class="row">-->
<!--    <div class="col mb-3">-->
      <%#= form.label :still_employed %>
      <%#= form.check_box :still_employed %>
<!--    </div>-->
<!--  </div>-->
  <div class="row">
    <div class="col mb-3">
      <%= form.label :primary_phone %>
      <%= form.text_field :primary_phone, value: @person.primary_phone, class: 'form-control', required: true %>
    </div>
    <div class="col mb-3">
      <%= form.label :alt_phone %>
      <%= form.text_field :alt_phone, value: @person.alt_phone, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col mb-3">
      <%= form.label :designated_role %>
      <%= form.select :designated_role, options_for_select(roles),prompt:params[:designated_role], :class => 'form-control', required: true   %>
    </div>
    <div class="col mb-3">
      <%= form.label :employment_date %>
      <%= form.date_field :employment_date,:class => 'form-control', value: @person.employee.employment_date rescue " " %>
    </div>
  </div>
  <div class="row">
    <div class="col mb-3">
      <%= form.label :branch %>
      <%= form.select :branch, options_for_select(branches),prompt:@employee.current_branches,
                      :class => 'form-control', required: true   %>
    </div>
    <div class="col mb-3">
      <%= form.label :department %>
      <%= form.select :department, options_for_select(departments), prompt:@employee.current_department,
                      :class => 'form-select', required: true rescue " " %>
    </div>
  </div>
  <div class="row">
    <div class="col mb-3">
      <%= form.label :marital_status %>
      <%= form.select :marital_status, options_for_select(marital_options), prompt:@person.marital_status, :class => 'form-select', required: true   %>
    </div>
    <div class="col mb-3">
      <%= form.label :residential_address %>
      <%= form.text_field :residential_address, value: @person.residential_address, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col mb-3">
      <%= form.label :supervisor %>
      <%= form.select :supervisor, options_for_select(supervisors), prompt:@employee.current_supervisors, :class => 'form-select', required: true   %>
    </div>
<!--    <div class="col mb-3">-->
      <%#= form.label :started_on %>
      <%#= form.date_field :started_on, value: , :class => 'form-select', required: true rescue " " %>
<!--    </div>-->
  </div>
  <div class="mb-3 mt-4">
    <%= form.hidden_field :person_id, value: @person.id %>
    <%= form.submit "Update", class: "btn btn-success btn-block" %>
    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
  </div>
<% end%>

app/views/employees/_progress_bar.html.erb
<style>
  .progress-bar {
    transition: width 0.5s ease-in-out;
  }
</style>
<div class="progress mb-3">
  <div id="progress-bar" class="progress-bar" role="progressbar" 
       style="width: 0%;" 
       aria-valuenow="0" 
       aria-valuemin="0" 
       aria-valuemax="100">
    0%
  </div>
</div>

app/views/employees/_remote_model.html.erb
<%= turbo_frame_tag "remote_modal" do %>

  <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/employees/_summary.html.erb
<style>
.snackbar {
  visibility: hidden;
  min-width: 250px;
  background-color: #333;
  color: #fff;
  text-align: center;
  border-radius: 5px;
  padding: 16px;
  position: fixed;
  z-index: 1000;
  bottom: 30px;
  left: 50%;
  transform: translateX(-50%);
  font-size: 16px;
}

.snackbar.show {
  visibility: visible;
  animation: fadein 0.5s, fadeout 0.5s 2.5s;
}

@keyframes fadein {
  from { bottom: 0; opacity: 0; }
  to { bottom: 30px; opacity: 1; }
}

@keyframes fadeout {
  from { bottom: 30px; opacity: 1; }
  to { bottom: 0; opacity: 0; }
}
</style>

<%# personal demographics %>
<div class="container mt-2">
  <div class="card shadow-lg p-3 mb-3 bg-white rounded">
    <div class="card-body">
      <h5 class="card-title">Personal Demographics</h5>
      <hr>
      <div class="row">
        <div class="col-md-4">  <p class="card-text"><strong>First Name:</strong> <span id="summary-first-name">---</span></p>
          <p class="card-text"><strong>Middle Name:</strong> <span id="summary-middle-name">--</span></p>
          <p class="card-text"><strong>Last Name:</strong> <span id="summary-last-name">--</span></p>
          <p class="card-text"><strong>Birthdate:</strong> <span id="summary-birth-date">--</span></p>
          <p class="card-text"><strong>Gender:</strong> <span id="summary-gender">--</span></p>
          <p class="card-text"><strong>Marital Status:</strong> <span id="summary-marital-status">--</span></p>
        </div>
        <div class="col-md-4">  <p class="card-text"><strong>Alternative Number:</strong> <span id="summary-alt-phone">--</span></p>
          <p class="card-text"><strong>Email:</strong> <span id="summary-email">--</span></p>
          <p class="card-text"><strong>Postal Address:</strong> <span id="summary-postal-address">--</span></p>
          <p class="card-text"><strong>Official Email:</strong> <span id="summary-official-email">--</span></p>
        </div>
        <div class="col-md-4">  <p class="card-text"><strong>Residential:</strong> <span id="summary-residential-address">--</span></p>
          <p class="card-text"><strong>Landmark:</strong> <span id="summary-landmark">--</span></p>
        </div>
      </div>
    </div>
  </div>
</div>

<%# employee details %>
<div class="container mt-2">
  <div class="card shadow-lg p-3 mb-3 bg-white rounded">
    <div class="card-body">
      <h5 class="card-title">Employee Details</h5>
      <hr>
      <div class="row">
        <div class="col-md-4">  <p class="card-text"><strong>Employment Date:</strong> <span id="summary-employment-date">---</span></p>
          <p class="card-text"><strong>Designated Role:</strong> <span id="summary-designated-role">--</span></p>
          <p class="card-text"><strong>Disignated Start Date:</strong> <span id="summary-designated-start-date">--</span></p>
        </div>
        <div class="col-md-4">  <p class="card-text"><strong>Branch:</strong> <span id="summary-branch">---</span></p>
            <p class="card-text"><strong>Department:</strong> <span id="summary-department">--</span></p>
        </div>
      </div>
    </div>
  </div>
</div>

<%# level of effort %>
<div class="container mt-2">
  <div class="card shadow-lg p-3 mb-3 bg-white rounded">
    <div class="card-body">
      <h5 class="card-title">Level of Effort</h5>
      <hr>
      <div class="row">
          <p class="card-text"><strong>Project:</strong> <span id="summary-project">--</span></p>
          <p class="card-text"><strong>Allocated Effort:</strong> <span id="summary-allocated-effort">--</span></p>
      </div>
    </div>
  </div>
</div>

<%# supervision %>
<div class="container mt-2">
  <div class="card shadow-lg p-3 mb-3 bg-white rounded">
    <div class="card-body">
      <h5 class="card-title">Supervion</h5>
      <hr>
      <div class="row">
          <p class="card-text"><strong>supervisor:</strong> <span id="summary-supervisor">--</span></p>
          <p class="card-text"><strong>Started on:</strong> <span id="summary-started-on">--</span></p>
      </div>
    </div>
  </div>
</div>


<div id="snackbar" class="snackbar">
  <%= flash[:notice] || flash[:alert] %>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
  var snackbar = document.getElementById("snackbar");
  if (snackbar.textContent.trim() !== "") {
    snackbar.classList.add("show");
    setTimeout(function () {
      snackbar.classList.remove("show");
    }, 3000);
  }
});
</script>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/edit.html.erb
<%= render "remote_model", title: "Edit Task to Timesheet" do %>
  <%= render "edit_employee" %>
<% end %>

app/views/employees/new.html.erb
<%= form_with url: employees_path,  method: :post , local: false do |form| %>

  <p class="h5 ">New Employee Form</p>
  <!-- Progress Bar -->
  <div class="progress mb-3">
    <div id="progress-bar" class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
  </div>


  <div class="card w-100">
    <div class="card">
        <div class="card-header card-header-dark">
          <nav>
            <div class="nav nav-tabs " id="nav-tab" role="tablist">
              <button class="nav-link active" id="nav-personal-demographics-tab" data-bs-toggle="tab" data-bs-target="#nav-personal-demographics" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">1. Personal Demographics</button>
              <button class="nav-link" id="nav-employment-details-tab" data-bs-toggle="tab" data-bs-target="#nav-employment-details" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">2. Employment Details</button>
              <button class="nav-link" id="nav-level-effort-tab" data-bs-toggle="tab" data-bs-target="#nav-level-effort" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">3. Levels of Effort</button>
              <button class="nav-link" id="nav-supervision-tab" data-bs-toggle="tab" data-bs-target="#nav-supervision" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">4. Supervision</button>
              <button class="nav-link" id="nav-summary-tab" data-bs-toggle="tab" data-bs-target="#nav-summary" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">5. Summary</button>
            </div>
          </nav>
        </div>

        <hr>


        <div class="card-body">
          <div class="tab-content" id="nav-tabContent">

            <%# personal demographics %>
            <div class="tab-pane active" id="nav-personal-demographics" role="tabpanel" aria-labelledby="nav-personal-demographics-tab">
              <div class="row">
                <div class="col-4">
                  <%= form.label :first_name, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[first_name]', class: "form-control required-field", placeholder: 'Enter first name' %>
                </div>
                <div class="col">
                  <%= form.label :middle_name, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[middle_name]', class: "form-control", placeholder: 'Enter middle name' %>
                </div>
                <div class="col-4">
                  <%= form.label :last_name, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[last_name]', class: "form-control required-field", placeholder: 'Enter last name' %>
                </div>
              </div>
              <div class="row mt-3">
                <div class="col-4">
                  <%= form.label :birth_date, style: "display: block", class: "form-label" %>
                  <%= form.date_field 'person[birth_date]', class: "form-control required-field", placeholder: 'Enter last name' %>
                </div>
                <div class="col-4">
                  <%= form.label :gender, style: "display: block", class: "form-label" %>
                  <%= form.select('person[gender]', gender_options, { include_blank: "Select gender"}, { :class => 'form-select', required: true  }) %>
                </div>
                <div class="col-4">
                  <%= form.label :marital_status, style: "display: block", class: "form-label" %>
                  <%= form.select('person[marital_status]', marital_options, { include_blank: "Select marital status"}, { :class => 'form-select', required: true }) %>
                </div>

              </div>
              <hr/>
              <div class="row mt-3">
                <div class="col-3">
                  <%= form.label :primary_phone, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[primary_phone]', class: "form-control required-field", placeholder: 'Enter primary phone no.' %>
                </div>
                <div class="col-3">
                  <%= form.label :alt_phone, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[alt_phone]', class: "form-control", placeholder: 'Enter alternative phone no.' %>
                </div>
                <div class="col">
                  <%= form.label :email_address, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[email_address]', class: "form-control required-field", placeholder: 'Enter personal email ' %>
                </div>
              </div>
              <div class="row mt-3">
                <div class="col">
                  <%= form.label :postal_address, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[postal_address]', class: "form-control required-field", placeholder: 'Enter postal address' %>
                </div>
                <div class="col">
                  <%= form.label :official_email, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[official_email]', class: "form-control", placeholder: 'Enter official email' %>
                </div>
              </div>
              <div class="row mt-3">
                <div class="col">
                  <%= form.label :residential_address, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[residential_address]', class: "form-control required-field", placeholder: 'Enter residential address' %>
                </div>
                <div class="col">
                  <%= form.label :landmark, style: "display: block", class: "form-label" %>
                  <%= form.text_field 'person[landmark]', class: "form-control required-field", placeholder: 'Enter landmark' %>
                </div>
              </div>

              <button type="button" class="btn btn-primary mt-3" onclick="buttonNavigate(1, 'next')">Next</button>

            </div>


            <!--2. Employement Details-->
            <div class="tab-pane" id="nav-employment-details" role="tabpanel" aria-labelledby="nav-employment-details-tab">
              <div class="row">
                <div class="row">
                  <div class="col-4">
                    <%= form.label :employment_date, style: "display: block", class: "form-label" %>
                    <%= form.date_field 'employee[employment_date]', class: "form-control required-field", placeholder: 'Enter employees employment date' %>
                  </div>
                  <div class="col">
                    <%= form.label :designated_role, style: "display: block", class: "form-label" %>
                    <%= form.select('employee[designated_role]', roles,  { include_blank: "Select role/position"}, { :class => 'form-select required-field', required: true }) %>
                  </div>
                  <div class="col-4">
                    <%= form.label :designation_start_date, style: "display: block", class: "form-label" %>
                    <%= form.date_field 'employee[designation_start_date]', class: "form-control required-field" %>
                  </div>
                  <div class="row mt-3">
                    <div class="col-4">
                      <%= form.label :branch, style: "display: block", class: "form-label" %>
                      <%= form.select('employee[branch]', branches, { include_blank: "Select branch"}, { :class => 'form-select required-field', required: true }) %>
                    </div>
                    <div class="col">
                      <%= form.label :departments, style: "display: block", class: "form-label" %>
                      <%= form.select('employee[departments]', departments, { include_blank: "Select department"}, { :class => 'form-select required-field', required: true }) %>
                    </div>
                  </div>
                </div>
              </div>
              <button type="button" class="btn btn-secondary mt-3" onclick="buttonNavigate(2, 'previous')">Previous</button>
              <button type="button" class="btn btn-primary mt-3" onclick="buttonNavigate(2, 'next')">Next</button>
            </div>


            <!--3. Level of Effort-->


            <%# LOE2 %>
            <%# container for available projects %>
              <select id="projectList" hidden>
                <option value="">Select project</option>
                <% projects.each do |project| %>
                  <option value="<%= project %>"><%= project %></option>
                <% end %>
              </select>

              <div class="tab-pane" id="nav-level-effort" role="tabpanel" aria-labelledby="nav-level-effort-tab">
                <div id="dynamicForm">

                  <div id="form-rows">
                    <div class="row mt-3">
                      <div class="col-4">
                        <%= label_tag 'projects', "Project", class: "form-label" %>
                        <%puts projects.inspect%>
                        <%= form.select('projects[][project]', projects,{ include_blank: "Select project"}, {class: 'form-control required-field', required: true}) %>
                      </div>
                      <div class="col-4">
                        <%= label_tag "allocated_effort", "Allocated Effort", class: "form-label" %>
                        <%= number_field_tag "projects[][allocated_effort]", nil, step:25, max: 100, min: 25, class: 'form-control required-field', required: true %>
                      </div>
                    </div>
                  </div>


                  <button type="button" class="btn btn-secondary mt-3" onclick="buttonNavigate(3, 'previous')">Previous</button>
                  <button type="button" id="submit-button" class="btn btn-primary mt-3" onclick="buttonNavigate(3, 'next')">Next</button>
                  <button type="button" class="btn btn-warning mt-3" id="total-effort-display" disabled>0%</button>
                </div>  
              </div>


            <!--Supervision-->
            <div class="tab-pane" id="nav-supervision" role="tabpanel" aria-labelledby="nav-supervision-tab">
              <div class="row">
                <div class="col-4">
                  <%= form.label :supervisor, style: "display: block", class: "form-label" %>
                  <%= form.select('supervision[supervisor]', supervisors, { include_blank: "Select supervisor"}, { :class => 'form-select required-field', required: true }) %>
                </div>
                <div class="col-4">
                  <%= form.label :started_on, style: "display: block", class: "form-label" %>
                  <%= form.date_field 'supervision[started_on]', class: "form-control required-field" %>
                </div>
              </div>
              <hr/>


              <button type="button" class="btn btn-secondary mt-3" onclick="buttonNavigate(4, 'previous')">Previous</button>
              <button type="button" class="btn btn-primary mt-3" onclick="buttonNavigate(4, 'next')">Next</button>
            </div>

            <%# summary %>
            <div class="tab-pane" id="nav-summary" role="tabpanel" aria-labelledby="nav-summary-tab" style="padding: 0; margin:0">
              <%= render 'employees/summary'%>              
              <button type="button" class="btn btn-secondary mt-3" onclick="buttonNavigate(5, 'previous')">Previous</button>
              <%= form.submit "Submit", class: "btn btn-success btn-block mt-3" %>
            </div>
            
          </div>
        </div>
    </div>
  </div>
<% end %>
<%= render 'employees/scripts'%>