config/routes.rb
Rails.application.routes.draw do

  # get 'user_sessions/new'
  # get 'user_sessions/create'
  resources :users #, only: [:index, show]
  resources :projects
  resources :branches
  resources :employees
  resources :timesheets
  #resources :requisitions
  resources :leave_requests
  resources :inventory_items
  resources :inventory_item_categories
  resources :inventory_item_thresholds
  resources :inventory_item_types
  resources :project_tasks
  resources :business_assets
  resources :time_sheet_tasks
  resources :project_task_assignments
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'travel_requests/new', to: 'travel_requests#new', as: :save_budget_details
  post 'travel_requests/create', to: 'travel_requests#create', as: :create_travel_requests
  get 'travel_requests/:id', to: 'travel_requests#show', as: :travel_request_show

  
  put 'timesheets/:id/submit_timesheet', to: 'timesheets#submit_timesheet'
  put 'timesheets/:id/approve_timesheet', to: 'timesheets#approve_timesheet'
  put 'timesheets/:id/reject_timesheet', to: 'timesheets#reject_timesheet', as: :reject_timesheet
  put 'timesheets/:id/recall_timesheet', to: 'timesheets#recall_timesheet'
  put 'timesheets/:id/re-open_timesheet', to: 'timesheets#reopen_timesheet'
  put 'timesheets/:id/re-submit_timesheet', to: 'timesheets#resubmit_timesheet'
  get 'my_timesheet', to: 'timesheets#show', as: :my_timesheet

  get 'settings/index'
  get 'settings/new'
  post 'settings/create'
  get 'settings/edit'

  get 'requisitions', to: 'requisitions#index'
  get 'requisitions/new', to: 'requisitions#new', defaults: { format: :turbo_stream }
  post 'requisitions/create'
  get 'requisitions/:id', to: 'requisitions#show'
  get 'requisitions/edit'
  patch 'requisitions/:id', to: 'requisitions#resubmit_request', as: :resubmit_request_requisition
  post '/clear_flash', to: 'application#clear_flash', as: :clear_flash

  put 'requisitions/:id/approve_request', to: 'requisitions#approve_request'
  put 'requisitions/:id/re-submit_request', to: 'requisitions#resubmit_request'
  put 'requisitions/:id/approve_funds', to: 'requisitions#approve_funds'
  put 'requisitions/:id/deny_funds', to: 'requisitions#deny_funds'
  put 'requisitions/:id/release_funds', to: 'requisitions#release_funds'
  put 'requisitions/:id/rescind_request', to: 'requisitions#rescind_request'
  put 'requisitions/:id/reject_request', to: 'requisitions#reject_request'
  put 'requisitions/:id/recall_request', to: 'requisitions#recall_request'
  put 'requisitions/:id/collect_funds', to: 'requisitions#collect_funds'
  put 'requisitions/:id/disburse_funds', to: 'requisitions#disburse_funds'
  patch 'requisitions/:id/liquidate_funds', to: 'requisitions#liquidate_funds', as: :liquidate_funds_requisition

  namespace :requisitions do
    resources :purchase_requests do
      member do
        # Define custom routes for purchase_requests here
      end
    end
  end

  put 'leave_requests/:id/approve_leave', to: 'leave_requests#approve_leave'
  put 'leave_requests/:id/cancel_leave', to: 'leave_requests#cancel_leave'
  put 'leave_requests/:id/deny_leave', to: 'leave_requests#deny_leave'
  put 'leave_requests/:id/rescind_request', to: 'leave_requests#rescind_request'

  get 'reports/index'
  get 'reports/new'
  get 'reports/create'
  get 'reports/edit'
  get 'reports/monthly_org_loe_report'

  get 'users/index'
  get 'forgot_password', to: 'users#forgot_password'
  post 'password_reset_forget', to: 'users#password_reset_forget'
  put 'users/:id/password_reset', to: 'users#password_reset'
  get 'main/home'
  get 'about', to: 'main#about'

  get "generate_report", to: 'reports#show', as: "generate_report", defaults: { format: :turbo_stream }

  get "logout", to: "user_sessions#destroy"
  resources :asset_categories

  get 'tc_dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "main#home"
end

app/models/timesheet_task.rb
class TimesheetTask < ApplicationRecord
  belongs_to :project, foreign_key: :project_id
  belongs_to :timesheet, foreign_key: :timesheet_id
end

app/controllers/time_sheet_tasks_controller.rb
class TimeSheetTasksController < ApplicationController
  def index
  end

  def new
    #raise @date.inspect
    @time_sheet_task = TimesheetTask.find(params[:time_sheet_id]) rescue nil
    @project_options = Project.all.collect { |x| [x.project_name, x.id] }
    @selected_project = Project.find_by_short_name(params[:prj])
    @timesheet = Timesheet.find(params[:time_sheet])
  end

  def create    
    new_time_sheet_task =  TimesheetTask.new(task_date: params[:task_date], project_id: params[:project_id] ,
                                                timesheet_id: params[:time_sheet_id],
                                                description: params[:description], duration: params[:duration])
    approved_leave = LeaveRequest.where(status: 31)
    approved_leave
    if new_time_sheet_task.save
      flash[:notice] = "Successfully recorded task in time sheet."
    else
      flash[:error] = "Failed to record task in time sheet."
    end
       
    redirect_to "/time_sheets/#{new_time_sheet_task.timesheet_id}"
  end

  def edit
    @time_sheet_task = TimesheetTask.find(params[:time_sheet_task_id])
    @project_options = Project.all.collect { |x| [x.project_name, x.id] }
    @timesheet = @time_sheet_task.timesheet
  end

  def update
    @time_sheet_task = TimesheetTask.find(params[:id])
    #checking if description has changed
    if @time_sheet_task.description != params[:description] || @time_sheet_task.project_id != params[:project_id]
      old_description = @time_sheet_task.description
      #find all related tasks with the old
      #batch update timesheettask with new description
      if TimesheetTask.where(description: old_description, project_id: @time_sheet_task.project_id,
                             timesheet_id: @time_sheet_task.timesheet_id).update_all(description: params[:description])

        flash[:notice] = "Successfully updated task and related tasks in time sheet."

      end
    end

    if @time_sheet_task.update(project_id: params[:project_id], task_date: params[:task_date],
                               timesheet_id: params[:time_sheet_id],duration: params[:duration])
      flash[:notice] = "Successfully updated task and related tasks in time sheet."
      redirect_to timesheet_path(@time_sheet_task.timesheet_id)
    else
      flash[:error] = "Error updating task."
      redirect_to timesheet_path(@time_sheet_task.timesheet_id)
    end
  end

  def destroy
    @time_sheet_task = TimesheetTask.find(params[:id])
    if @time_sheet_task.destroy
      flash[:alert] = "deleted successfully"
      redirect_to "/time_sheets/#{@time_sheet_task.timesheet_id}"
    else
      flash[:alert] = "error deleting task"
      respond_to do |format|
        format.html { redirect_to timesheet_path(@time_sheet_id.timesheet_id) }
        format.js
      end
    end
  end

  private

  def task_params
    params.require(:time_sheet_task).permit(:description, :project_id, :task_date, :duration, :time_sheet_id, :time_sheet_task)
  end
  
end

app/helpers/time_sheet_tasks_helper.rb
module TimeSheetTasksHelper
end

app/views/time_sheet_tasks/_edit_form.erb
<%= form_with model: @timesheet_task, method: "PUT",  url: "/time_sheet_tasks/#{@time_sheet_task.id}" , data: {'turbo-frame' => '_top'} do |form|%>

  <div class="row">
    <div class="col mb-3">
      Select Project
    </div>
    <div class="col mb-3">
      <%= form.label :project_id%>
      <%= form.select :project_id, options_for_select(@project_options, (@time_sheet_task.project_id rescue nil)),
                      prompt:@time_sheet_task.project.short_name, :class => 'form-select', required: true   %>
    </div>
  </div>
  <div class="row">
    <div class="col mb-3">
      <%= form.label :task_date %>
      <%= form.date_field :task_date, value: @time_sheet_task.task_date, min: @timesheet.timesheet_week.beginning_of_week,
                          max: @timesheet.timesheet_week.end_of_week, class: 'form-control', required: true %>
    </div>
    <div class="col mb-3">
      <%= form.label :duration %>
      <%= form.number_field :duration, value: @time_sheet_task.duration, step:0.25, max: 18, min: 0, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= form.label :description %> 
      <%= form.text_field :description, value: @time_sheet_task.description, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="mb-3 mt-4">
    <%= form.hidden_field :time_sheet_id, value: @time_sheet_task.timesheet_id %>
    <%= form.submit "Update", class: "btn btn-success btn-block" %>
    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
  </div>
<% end %>

app/views/time_sheet_tasks/_form.html.erb
<%= form_with model: @timesheet_task, url: time_sheet_tasks_path do |form| %>

  <div class="row">
    <div class="col mb-3">
      Select Project
    </div>
    <div class="col mb-3">
      <%= form.select :project_id, options_for_select(@project_options, (@selected_project.id rescue nil)),
                      prompt:(@selected_project.full_name rescue params[:"prj"]),
      :class => 'form-select', required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col mb-3">
      <%= form.label :task_date %>
      <%= form.date_field :task_date, value: params[:day],min: @timesheet.timesheet_week.beginning_of_week,
                          max: @timesheet.timesheet_week.end_of_week, class: 'form-control', required: true %>
    </div>
    <div class="col mb-3">
      <%= form.label :duration %>
      <%= form.number_field :duration, step:0.25, max: 18, min: 0, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= form.label :description %>
      <%= form.text_field :description, value: params[:"tsk_desc"], class: 'form-control', required: true %>
    </div>
  </div>
  <div class="mb-3 mt-4">
    <%= form.hidden_field :time_sheet_id, value: params[:"time_sheet"] %>
    <%= form.submit "Save", class: "btn btn-success btn-block" %>
    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
  </div>
<% end %>

app/views/time_sheet_tasks/create.html.erb
<h1>TimeSheetTasks#create</h1>
<p>Find me in app/views/time_sheet_tasks/create.html.erb</p>

app/views/time_sheet_tasks/edit.html.erb
<h1>TimeSheetTasks#edit</h1>
<!--<p>Find me in app/views/time_sheet_tasks/edit.html.erb</p>-->

<%= render "remote_model", title: "Edit Task to Timesheet" do %>
  <%= render "edit_form" %>
<% end %>

app/views/time_sheet_tasks/index.html.erb
<h1>TimeSheetTasks#index</h1>
<p>Find me in app/views/time_sheet_tasks/index.html.erb</p>

app/views/time_sheet_tasks/new.html.erb
<h1>Add Task to Timesheet </h1>
<%= render "remote_model", title: "Add Task to Timesheet" do %>
  <%= render "form" %>
<% end %>